name: 'Lint tests'

on:
  push:
    branches: [develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.0

      - name: Use Node.js
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 16.x

      - name: Install packages
        run: npm ci

      - name: Next.js linting
        run: npm run lint:next

      - name: Prettier linting
        run: npm run lint:prettier

      - name: Stylelint linting
        run: npm run lint:scss
